### PR TITLE
prometheus-adapter: Collect metrics from Prometheus Adapter

### PR DESCRIPTION
**Pull request by brancz**
@coreos/team-monitoring

### CODE REVIEW

**Comment by paulfantom** [comment]
Could you run generate again. Seems like there is one thing missing:
```
diff --git a/kustomization.yaml b/kustomization.yaml
index 8047150..73ce56e 100644
--- a/kustomization.yaml
+++ b/kustomization.yaml
@@ -36,6 +36,7 @@ resources:
 - ./manifests/prometheus-adapter-roleBindingAuthReader.yaml
 - ./manifests/prometheus-adapter-service.yaml
 - ./manifests/prometheus-adapter-serviceAccount.yaml
+- ./manifests/prometheus-adapter-serviceMonitor.yaml
 - ./manifests/prometheus-clusterRole.yaml
 - ./manifests/prometheus-clusterRoleBinding.yaml
 - ./manifests/prometheus-operator-serviceMonitor.yaml
```

Otherwise LGTM :+1:

**Comment by metalmatze** [comment]
We weren't scraping the Prometheus Adapter itself? :flushed:

**Comment by s-urbaniak** [comment]
@metalmatze yes, and you can blame me :grimacing: (hide-and-duck)

**Comment by metalmatze** [comment]
Not blaming anyone, was just surprised. Glad it's there now :tada:

**Pull request merged**
