### PR TITLE
Link fixes

### PR DESCRIPTION
**Pull request by goll**
Initial attempt to fix links pointing to `prometheus-operator`.

### CODE REVIEW

**Comment by goll** [comment]
Also looks like this script is missing: `hack/scripts/generate-dashboards-configmap.sh`
https://github.com/coreos/kube-prometheus/blob/master/docs/monitoring-external-etcd.md#regenetate-the-grafana-dashboard-manifest

**Comment by brancz** [comment]
Actually all of step 3 can safely be removed. The jsonnet files already do that automatically :)

**Comment by brancz** [comment]
otherwise this lgtm

**Comment by brancz** [comment]
Wonderful, thanks a lot! lgtm :+1: :slightly_smiling_face:

**Pull request merged**
