### PR TITLE
Pin kubernetes-mixin v0.1.0

### PR DESCRIPTION
**Pull request by metalmatze**
We should use the released version of kubernetes-mixin. We can always release another kubernetes-mixin v0.1.x if we need anything updated.

### CODE REVIEW

**Comment by metalmatze** [comment]
This will be even more important once we start merging Kubernetes 1.14 patches to the kubernetes-mixin `master` branch and thus would break people by updating the project's dependency here.

**Comment by brancz** [comment]
We lock the exact version in the lock file already, here I would just “pin” against release-0.1, that’ll make updating a bit easier, especially for things that use the mixin as a transitive dependency.

**Comment by metalmatze** [comment]
Updated the PR to pin `release-0.1`. Hope the CI works, as I haven't generate again.

**Comment by brancz** [comment]
lgtm :+1:

**Pull request merged**
