### PR TITLE
chore(jsonnet): ⬆️  update jsonnet to master

### LINKED ISSUE #537: Grafana dashboards slows down Jsonnet build considerably
**What happened?**
Using this package with [google/go-jsonnet](https://github.com/google/go-jsonnet), the build times are inflated considerably by the inclusion of Grafana dashboards.

**Did you expect to see some different?**
I did not expect ~90% of the build time to go into Grafana dashboard expansion. There must be some particularly inefficient expression somewhere in there...

**How to reproduce it (as minimally and precisely as possible)**:
This is the out-of-the-box build on a mid-2011 iMac 27":

```console
$ time ./build.sh 
+ set -o pipefail
++ pwd
+ PATH=/Users/benoit/Documents/ubisoft/kube-prometheus/tmp/bin:/Users/benoit/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
+ rm -rf manifests
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests example.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
+ find manifests -type f '!' -name '*.yaml' -delete
+ rm -f kustomization

real	0m18.000s
user	0m31.897s
sys	0m1.152s
```

After removing all dashboards with this simple patch:

```diff
diff --git a/example.jsonnet b/example.jsonnet
index 54de1e3..36bd59c 100644
--- a/example.jsonnet
+++ b/example.jsonnet
@@ -11,6 +11,7 @@ local kp =
     _config+:: {
       namespace: 'monitoring',
     },
+    grafanaDashboards:: {},
   };
 
 { ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
```

The build time drops considerably:

```console
$ time ./build.sh 
+ set -o pipefail
++ pwd
+ PATH=/Users/benoit/Documents/ubisoft/kube-prometheus/tmp/bin:/Users/benoit/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
+ rm -rf manifests
+ mkdir -p manifests/setup
+ jsonnet -J vendor -m manifests example.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml' -- '{}'
+ find manifests -type f '!' -name '*.yaml' -delete
+ rm -f kustomization

real	0m2.611s
user	0m3.739s
sys	0m0.645s
```

I tried following the rabbit hole down `kubernetes/kubernetes-mixin` and `brancz/kubernetes-grafana` but I figured I'd start by opening an issue here.

### PR DESCRIPTION
**Pull request by ghostsquad**
pulls in recent performance improvement changes to speed up rendering

resolves #537

### CODE REVIEW

**Comment by paulfantom** [comment]
Personally I would prefer if we would use full release. Currently, we have `0.15.1-...` only to get rid of a containerized build pipeline as that that was a version which included `jsonnetfmt` written in golang.

**Comment by brancz** [comment]
just curious, could you link the performance improvement PRs? :)

**Comment by brancz** [comment]
sorry shouldn't have been so lazy, found it myself https://github.com/google/go-jsonnet/pull/422

**Comment by brancz** [comment]
I do agree with @paulfantom I would prefer if we do this bump only for a released version.

**Comment by ghostsquad** [comment]
@brancz Releases for go-jsonnet aren't tied to features, they are tied to "time", and only because of the long time it takes to perform a release (they really need to automate a bunch of it).

https://github.com/google/jsonnet/pull/802/files?short_path=0839b2d#diff-0839b2d87fd557256d6fafc90d0b4e72

So, if you want to wait for the sake of waiting... ok, I guess.

Anyways, I am the contributor that has been working on all the performance improvements in the last 6 months or so. 😄 

https://github.com/google/go-jsonnet/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Aghostsquad+is%3Aclosed

Just happy to help the community.

**Comment by brancz** [comment]
Had a quick chat with @paulfantom, and since all this does is speed up our CI, we're happy with moving forward.

Thanks so much for your extremely valuable contributions to the community!!! :tada:

**Comment by brancz** [comment]
@ghostsquad I just tried out this version with kube-prometheus, and I have to say I'm absolutely baffled. The performance improvements are incredible! Thank you so much for your amazing work!

**Pull request merged**
