### PR TITLE
Fix incorrect KubeVersionMismatch alert when `{job=coredns}`

### PR DESCRIPTION
**Pull request by minhdanh**
I'm following the steps in https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack#sync_prometheus_rulespy

To make the fix in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/231
merged to https://github.com/helm/charts/tree/master/stable/prometheus-operator

### CODE REVIEW

**Comment by brancz** [comment]
For CI to pass you need to bump the jsonnet dependency and follow these steps: https://github.com/coreos/kube-prometheus/blob/master/README.md#contributing

**Comment by minhdanh** [comment]
```
$ travis_export_go 1.12.x github.com/coreos/kube-prometheus

0.05s$ travis_setup_go

gimme: given '1.12.x' but no release for '1.12' found

gimme: given '1.12.x' but no release for '1.12' found

Failed to run gimme

The command "travis_setup_go" failed and exited with 86 during .

Your build has been stopped.
```

Hmm, I'm not sure what the error is about. Do you have any ideas?

**Comment by brancz** [comment]
Odd. I restarted the job to see if that was just a travis ci flake.

**Comment by brancz** [comment]
Thanks!

**Pull request merged**
