### PR TITLE
change to use GA kubelet OS label

### PR DESCRIPTION
**Pull request by rphillips**
change to use the GA kubelet OS label

ref: https://github.com/openshift/cluster-monitoring-operator/issues/371
ref: https://jira.coreos.com/browse/NODE-114

### CODE REVIEW

**Comment by squat** [comment]
It seems that you manually changed the node selectors in the generated manifests. In order for the generation to work, we need to bump the hash in https://github.com/coreos/kube-prometheus/blob/master/jsonnetfile.lock.json#L11

This is because the example manifests vendor kube-prometheus itself. After updating the hash to the hash of you commit that introduces the libsonnet changes, regenerate and commit that result in a “regenerate” commit. Making jsonnet changes to the repo itself is currently always a two-step process, but this is largely a limitation of jb today and will be improved soon.

**Comment by rphillips** [comment]
@squat thanks for the tip! updated the PR and regenerated.

**Comment by rphillips** [comment]
`wait for prometheus-k8s: timed out waiting for the condition`...

/retest

**Comment by rphillips** [comment]
Strange... same error. Thoughts?

**Comment by brancz** [comment]
Is kube 1.13 maybe not new enough?

**Comment by rphillips** [comment]
Kube 1.14 is needed for this feature.

**Comment by brancz** [comment]
I see kind node v1.13 in the build logs. Can you upgrade this?

**Comment by brancz** [comment]
Awesome! lgtm :+1: thanks!

**Pull request merged**
