### PR TITLE
Bump dependencies 

### PR DESCRIPTION
**Pull request by lilic**
This is to bump all the dependencies before the release is cut. 

cc @coreos/team-monitoring @dgrisonnet

### CODE REVIEW

**Comment by lilic** [comment]
Ready for review @coreos/team-monitoring @dgrisonnet  PTAL, had to bump the go version as well as that was the only way tests passed for, as i am using 1.13.

**Comment by brancz** [comment]
I expected to see a pin to kubernetes-mixin `release-0.4`. Any reason why it's not here?

**Comment by lilic** [comment]
I guess I can do that in the same PR, was thinking of doing a bump and another of for cutting the release itself.

**Comment by brancz** [comment]
That works for me as well.

**Pull request merged**
