### PR TITLE
Use ksonnet.beta.4 with updated Kubernetes 1.14

### PR DESCRIPTION
**Pull request by metalmatze**
We are still blocked on https://github.com/ksonnet/ksonnet-lib/pull/160. I would say we give that PR a couple of more days and see if we can unblock this one. The we don't need to workaround by adding another dependency called `ksonnet4`.

/cc @squat @mxinden @paulfantom @brancz

### CODE REVIEW

**Comment by brancz** [comment]
Nice!

**Comment by bgagnon** [comment]
ksonnet/ksonnet-lib#160 is merged! looking forward to this!

**Comment by brancz** [comment]
this needs an update but then should be ready to merge :tada:

**Comment by metalmatze** [comment]
Moved to upstream `ksonnet.beta.4` and rebased against current master.

**Pull request merged**
