### PR TITLE
Remove Thanos components except sidecar

### PR DESCRIPTION
**Pull request by metalmatze**
Now that we have [kube-thanos](https://github.com/metalmatze/kube-thanos) we don't need to have Thanos components in this project, except the sidecar (as that is something specific to the way kube-prometheus deploys Prometheus).
All the other components like Querier, Store, Receive, Ruler and Compactor should come from the more focused project kube-thanos. This includes things like ServiceMonitors too.

/cc @brancz @kakkoyun

### CODE REVIEW

**Comment by brancz** [comment]
We should update docs as well (RE: #2667)

cc @RiRa12621

**Comment by RiRa12621** [comment]
i'll update https://github.com/coreos/prometheus-operator/pull/2667 once this one is merged

**Comment by brancz** [comment]
oops, wrong order, sorry

**Comment by brancz** [comment]
@RiRa12621 feel free to create a new PR :)

**Comment by RiRa12621** [comment]
is there plans to move out of https://github.com/metalmatze/kube-thanos under an Org @metalmatze because then I'd hold with the doc pr until that's done.

**Comment by brancz** [comment]
Not for now, but eventually yes (@metalmatze I'd be ok moving it to the coreos org)

**Comment by metalmatze** [comment]
Yep. I don't really care where it lives :innocent:

**Comment by benjaminhuo** [comment]
ops, thanos has been moved to a new project...

**Pull request merged**
