### PR TITLE
Generate k8s config & operator v0.6.0

### PR DESCRIPTION
**Pull request by brancz**
Besides moving the Prometheus config generation to `ServiceMonitor`s this updates the Prometheus Operator to the latest release and updates the resources to reflect the changes of the release.

@alexsomesan @fabxc

### CODE REVIEW

**Comment by brancz** [comment]
Updated to use latest version of Prometheus, but we can probably hold off on this until the kube-state-metrics release is done.

**Comment by dmcnaught** [comment]
I ran `./hack/cluster-monitoring/deploy` and `kubectl --namespace=kube-system apply -f manifests/k8s/self-hosted`
Everything looks good, but compared to master, PR33 looses kube-state-metrics, kubelets, node-exporter and prometheus from targets.
The cert issue on the apiserver (kubernetes) target doesn't show up.
One alert shows: `K8SKubeletDown (1 active)`

**Comment by dmcnaught** [comment]
Grafana looks to have no data ^

**Comment by fabxc** [comment]
Sweet 🎉  👍

**Pull request merged**
