### PR TITLE
Fix prometheus-operator’s git sha to use v0.30.0

### PR DESCRIPTION
**Pull request by MerelyAPseudonym**
Fixes [#105](https://github.com/coreos/kube-prometheus/issues/105)

Let me know if there should also be a commit to update the kube-prometheus version in the `jsonnetfile.lock.json`—something like:
```diff
@@ -8,7 +8,7 @@
                     "subdir": "jsonnet/kube-prometheus"
                 }
             },
-            "version": "81b9c9f9f6886ba1fbd61b05cdf0cc4f4d95eba8"
+            "version": "24c21574823556526d8eb486ff02be1e7df8af72"
         },
         {
             "name": "ksonnet",
```

Also, if you do approve of this fix, how would you feel about cutting a v0.1.1 release?

### CODE REVIEW

**Comment by brancz** [comment]
cc @metalmatze

**Comment by metalmatze** [comment]
It would be great, if we could actually reference `release-0.30` in [jsonnet/kube-prometheus/jsonnetfile.json](https://github.com/coreos/kube-prometheus/blob/release-0.1/jsonnet/kube-prometheus/jsonnetfile.json#L41) and then run `jb update` again. Then we'll already forward to v0.30.1 :blush: 

Otherwise this LGTM :+1:

**Comment by brancz** [comment]
Thank you! lgtm :+1:

**Comment by MerelyAPseudonym** [comment]
@metalmatze @brancz sounds great! I'll make those changes and update my branch shortly.

**Comment by MerelyAPseudonym** [comment]
@metalmatze @brancz The branch should be good to go.

**Comment by brancz** [comment]
lgtm thanks!

**Pull request merged**
