### PR TITLE
Use prebuilt container with jsonnet in it

### PR DESCRIPTION
**Pull request by paulfantom**
Reuse container built from Dockerfile in prometheus-operator.

Propagated from https://github.com/coreos/prometheus-operator/pull/2601

/cc @brancz @metalmatze @s-urbaniak @squat

### CODE REVIEW

**Comment by squat** [comment]
Hmm it looks like this causes a delta in the Go mod file

**Comment by paulfantom** [comment]
Now it works :) We didn't need to set `GO111MODULE=on` for generation phase.

**Comment by brancz** [comment]
Nice!

**Comment by sbeekhuis** [comment]
I think this merge request made this part of the documentation out of date:
https://github.com/coreos/kube-prometheus#containerized-installing-and-compiling

If I want to generate manifests from a docker container what workflow should I use now. 
I'm trying `make generate-in-docker`. But I'm not sure if it's doing the same thing.

Also it it's doing the right thing how do I get it to pick up the right jsonnet file to build manifests from?

Thanks in advance,

PS If I need to create a new issue for this I can/will do so. But my issue seem related to this change.
PPS If this workflow is no longer supported that's okay I guess. Then I'll just build on my own machine.

**Comment by paulfantom** [comment]
I added updated instructions in #104. @sbeekhuis please use that ones and sorry for inconvenience

**Pull request merged**
