### PR TITLE
Update manifests to latest version of Prometheus Operator

### PR DESCRIPTION
**Pull request by brancz**
Tried out with a container image of `HEAD` of the Prometheus Operator.

List of changes divided into commits:
* Set lower resource requests by default (simply for demo purposes, as this currently won't work on minikube for example with only 1Gb of memory)
* Remove unnecessary prometheus.io/scrape annotation: (tl;dr) more confusing then helpful
* Add Alertmanager support in TPRs and manifests themselves (recently added to Prometheus Operator)
* Add kube-dns service for skydns and dnsmasq metrics to be collected. This change reflects work [upstream](https://github.com/kubernetes/kubernetes/blob/545f749a0deb8535656ce93ac1f35a59887839bf/cluster/addons/dns/skydns-rc.yaml.sed) and on [bootkube](https://github.com/kubernetes-incubator/bootkube/pull/179).
* Update `node-exporter` version

It would probably make sense to cut another release of the Prometheus Operator, just so we can at least partially version this until we get versioned user-guides.

@fabxc

### CODE REVIEW

**Comment by fabxc** [comment]
👍 looks good.

Yes, we should cut another version to integrate into Tectonic etc.

**Comment by julianvmodesto** [comment]
@brancz sorry if this isn't the best place to ask!

Regarding 0c1bb5c, why were prometheus.io/scrape annotations removed? Is there any way to configure Prometheus Operator to discover pods to scrape based on these annotations still?

**Comment by fabxc** [comment]
The annotation is not supported by the operator. ServiceMonitors should be
used instead. The annotation is very limited by its nature and there's no
feasible way to support anything beyond "scrape on" and a single port. A
per-service scrape interval, multi-port pods, authentication, honorLabels,
and more are all not possible. It also provides no meaningful way to assign
services to be scraped by different Prometheus instances.

ServiceMonitors allow all these without exposing any complex relabelling
and there's really no practical reason for sticking with the annotation.

**Comment by julianvmodesto** [comment]
Got it – this is helpful and makes sense after consuming, thank you!

**Comment by cornelius-keller** [comment]
The problem I see here is that this annotations are fully self service and a well working way to communicate the metrics that should be scraped to prometheus. With ServiceMonitors this self service is not working anymore as they need to be in the monitoring namespace and I don't want to give everybody access to it.
As discussed here: https://github.com/coreos/prometheus-operator/pull/813 .
So for me regarding ease of setup etc. prometheus-operator is a great step, regarding the self service kapabilities that my previeous setup had it is a step back.

**Comment by brancz** [comment]
The ServiceMonitor has a namespaceselector for the services, so the only thing you to do is have a convention in your organization, which boils down to the same as the annotation. You simply need you organization to have a commonly named port and a label like "monitoring: true". The namespace selector can then select Services globally.

**Comment by brancz** [comment]
However, we acknowledge the want that people have, and are trying to think of a way we can introduce something more broad without violating the concerns we currently have.

**Comment by StevenACoffman** [comment]
We have an established convention, but also often have third party tools installed which have their own conflicting conventions. As a hybrid solution, we are applying [a custom prometheus](https://github.com/Yolean/kubernetes-monitoring#custom-prometheus) on top of the operator. Thanks again @solsson

**Comment by maver1ck** [comment]
I'd like to add one more thing to this issue.
There is a lot of 3rd party tools and ready to use helm charts that are using annotations.
And we can't use it out of the box.

**Comment by StevenACoffman** [comment]
That is exactly our issue. 3rd party helm apps often have this need, which is in conflict with our using the operator at present.

**Comment by maver1ck** [comment]
I found following solution.
In prometheus helm chart configuration add this:
```
  additionalScrapeConfigs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```

**Comment by suppix** [comment]
@maver1ck Could you please tell me where I should put this configuration ?

**Comment by maver1ck** [comment]
You need to add this to helm chart configuration (values.yaml)
https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/values.yaml#L353

**Comment by absolutejam** [comment]
> I found following solution.
> In prometheus helm chart configuration add this:
> 
> ```
>   additionalScrapeConfigs:
>   - job_name: 'kubernetes-pods'
>     kubernetes_sd_configs:
>     - role: pod
>     relabel_configs:
>     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
>       action: keep
>       regex: true
>     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
>       action: replace
>       target_label: __metrics_path__
>       regex: (.+)
>     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
>       action: replace
>       regex: ([^:]+)(?::\d+)?;(\d+)
>       replacement: $1:$2
>       target_label: __address__
>     - action: labelmap
>       regex: __meta_kubernetes_pod_label_(.+)
>     - source_labels: [__meta_kubernetes_namespace]
>       action: replace
>       target_label: kubernetes_namespace
>     - source_labels: [__meta_kubernetes_pod_name]
>       action: replace
>       target_label: kubernetes_pod_name
> ```
> Then all pods with prometheus.io/scrape annotations are processed.
> You don't need custom prometheus for that :)

There is also some information available at [https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md)

**Comment by jmvizcainoio** [comment]
you can also add this config to scrape services

```
      - job_name: 'kubernetes-service'
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_service_name
```

**Comment by JulienBreux** [comment]
Update about `values.yaml` location; https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

**Comment by bchanson** [comment]
If you're compiling the yamls using the jsonnet file. Follow the [instructions mentioned earlier](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) to create the additional scrape config secret. 

I tried to patch the prometheus resource directly after building/applying the yamls via jsonnet. It didn't work. I had to add the `additionalScrapeConfigs` config to the jsonnet file. 

This does not go in the `_config+::` section. It goes in `prometheus+::` like the serviceMonitor definitions.

```jsonnet
    prometheus+:: {
      prometheus+: {
        spec+: {
          additionalScrapeConfigs+: {
            name: 'additional-scrape-configs',
            key: 'additonal-scrape-configs.yaml'
          },
        },
      },
    },
```

**Pull request merged**
