### PR TITLE
add tolerations

### PR DESCRIPTION
**Pull request by benjaminhuo**
Signed-off-by: Benjamin <benjamin@yunify.com>

### CODE REVIEW

**Comment by brancz** [comment]
This is a great example! It does seem pretty specific to your setup. I'd prefer if this was just documentation maybe, what do you think?

**Comment by benjaminhuo** [comment]
I've made some modifications to make it more generic and to suit more toleration cases. 
https://github.com/coreos/kube-prometheus/pull/102/commits/6f48bdb5a638cd8c4e122d68ae7e22427b4b476a

Let me know which doc you prefer to add it to , thanks. :)

Ben

**Comment by benjaminhuo** [comment]
@brancz I've moved the toleration to a new file named tolerations.libsonnet in examples folder.
Is it ok for you ? 

Thanks
Ben

**Comment by brancz** [comment]
yep that looks good! thanks!

**Pull request merged**
