### PR TITLE
prometheus-operator.libsonnet: Add PrometheusOperatorWatchErrors alert

### PR DESCRIPTION
**Pull request by lilic**
Not too sure about the threshold yet `0.1` might be a bit too aggressive, thoughts? 

cc @metalmatze @coreos/team-monitoring

### CODE REVIEW

**Comment by brancz** [comment]
Nice! lgtm

**Comment by paulfantom** [comment]
I think it's time we started a promethues-operator monitoring mixin. WDYT?

**Comment by lilic** [comment]
@paulfantom yes said the same thing to Matthias :D after this release I was planning on moving it to the promethues-operator monitoring mixin just to not mess up the releases.

**Comment by paulfantom** [comment]
Sorry, I was faster: https://github.com/coreos/prometheus-operator/pull/3333 :D

**Comment by lilic** [comment]
I would prefer to hold until after the next release of kube-prometheus.

**Comment by paulfantom** [comment]
> I would prefer to hold until after the next release of kube-prometheus.

We don't need to merge it into kube-prometheus yet ;)

**Pull request merged**
