### PR TITLE
Do not fix dependencies in root jsonnetfile

### LINKED ISSUE #296: Cannot jb update current master
**What happened?**
After cloning the new master (b8f513e4d485db099a1dec4dffd219518b4d8d57) `jb update` is failing with the error : 
```
>>> Installed node-mixin version 5a7b85876d6108a91f0d8673c0d7eca38687671b
jb: error: failed to install: failed to insert dependency to lock dependencies: multiple colliding versions specified for node-mixin: 20fe5bfb5be4caf3c8c11533b7fb35cb97d810f5 (from vendor/kube-prometheus/jsonnetfile.json) and 5a7b85876d6108a91f0d8673c0d7eca38687671b (from jsonnetfile.json)
```

**Did you expect to see some different?**
`jb update` should be successful with updated versions in the lock file.

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/coreos/kube-prometheus.git && cd kube-prometheus
jb update
```

**Environment**
OS : macOS Catalina Version `10.15`.
kube-prometheus : latest master (commit : b8f513e4d485db099a1dec4dffd219518b4d8d57)

### PR DESCRIPTION
**Pull request by s-urbaniak**
The root jsonnetfile had node mixin pinned as the node exporter mixin had an upstream bug. Since upstream bug has been fixed in https://github.com/prometheus/node_exporter/pull/1532 and pinning in the root jsonnetfile was wrong anyways, this unpins that dependency.

Along the way it updates the jsonnet dependencies and regenerates the manifests.

Fixes #296 

/cc @brancz @karancode

### CODE REVIEW

**Comment by s-urbaniak** [comment]
hmm, let me see :thinking:

**Comment by s-urbaniak** [comment]
ok, I did a subsequent `jb install` and could reproduce this. I cannot explain why the previous `jb update` and a subsequent `jb install` caused this inconsistency though :thinking:

**Comment by s-urbaniak** [comment]
@brancz ptal

**Comment by brancz** [comment]
I opened #299 which seems to pass. There is a new jb version, make sure you install master. Beyond that on new jb versions it's sometimes necessary to reset the whole environment (rm lockfile and vendor dir). Sorry about the inconvenience. I _think_ this should be the last breaking-ish change for a while.

**Comment by s-urbaniak** [comment]
closing in favor of #299

**Comment by s-urbaniak** [comment]
hmm ... i explicitly pulled newest master, but did not delete the lock file, just the vendor dir. good, we have it resolved now :+1:

**Pull request closed without merging**
