### PR TITLE
Fix typo in node-exporter DaemonSet

### PR DESCRIPTION
**Pull request by paulfantom**
follow-up to https://github.com/coreos/kube-prometheus/pull/326

### CODE REVIEW

**Comment by s-urbaniak** [comment]
lgtm

**Comment by brancz** [comment]
How come our e2e didn’t catch this?

**Comment by paulfantom** [comment]
> How come our e2e didn’t catch this?

We do not start a cluster in e2e here, so we don't have full validation of objects.

This was actually caught in e2e in https://github.com/openshift/cluster-monitoring-operator/pull/591

**Comment by paulfantom** [comment]
Because our e2e here doesn't validate node-exporter deployment: https://github.com/coreos/kube-prometheus/blob/master/tests/e2e/main_test.go#L66-L68

**Comment by brancz** [comment]
Can we enable that? :)

**Pull request merged**
