### PR TITLE
Update kubernetes-mixin for kube-apiserver-availability fixes

### LINKED ISSUE #503: code_verb:apiserver_request_total:increase30d is failing to evaluate
**What happened?**
I upgraded from an older version from a few months ago to the latest 0.5 release with jb and `Prometheus is failing rule evaluations` starting to fire immediately. I checked Prometheus and https://github.com/coreos/kube-prometheus/blob/dcc46c8aa8c242b845024188a66171b5f08b8513/manifests/prometheus-rules.yaml#L393 is in ERR state: `query processing would load too many samples into memory in query execution`

**Did you expect to see some different?**
The rule included shouldn't be failing

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**
GKE
* Prometheus Operator version:

    `v0.38.1`

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
`
`
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.5", GitCommit:"a5bf731ea129336a3cf32c3375317b3a626919d7", GitTreeState:"clean", BuildDate:"2020-03-31T02:49:49Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:

    GKE

`level=warn ts=2020-04-18T11:01:09.892Z caller=manager.go:525 component="rule manager" group=kube-apiserver.rules msg="Evaluating rule failed" rule="record: code_verb:apiserver_request_total:increase30d\nexpr: sum by(code, verb) (increase(apiserver_request_total{job=\"apiserver\"}[30d]))\n" err="query processing would load too many samples into memory in query execution"`

### PR DESCRIPTION
**Pull request by metalmatze**
Update kubernetes-mixin for latest fixes for kube-apiserver-availability.rules :)

Closes #503

### CODE REVIEW

**Comment by metalmatze** [comment]
Verified by running these fixes on my cluster for the last 4 days. Although I never had the problem with too many samples, I can confirm that these fixes at least from the outside don't change anything, but definitely improve things.

**Comment by den-is** [comment]
hey guys, any updates on this?

**Comment by joshbranham** [comment]
Running into this as well, can we get it merged?

**Comment by jetersen** [comment]
Been a while any update? I really do not like to mute as it hides the issue with container running around with wasteful logs or increase query sample as this simply overloads memory usage...

**Comment by metalmatze** [comment]
I'm still working on this. Trying to improve performance. Feel free to look at the upstream issue where we actually need to solve the problem. :blush:

**Comment by metalmatze** [comment]
Closing in favor of #590

**Pull request closed without merging**
