### PR TITLE
make node_exporter pods tolerate every taint

### PR DESCRIPTION
**Pull request by paulfantom**

### CODE REVIEW

**Comment by brancz** [comment]
Thanks! lgtm

**Comment by brancz** [comment]
Can you also patch the release-0.1 branch with this? Then we can use that to patch OpenShift 4.1

**Comment by paulfantom** [comment]
Sure, here it is: https://github.com/coreos/kube-prometheus/pull/127 :slightly_smiling_face:

**Comment by ttreptow** [comment]
I think this is missing a semicolon on line 70:
`vendor/kube-prometheus/node-exporter/node-exporter.libsonnet:71:7-12 Expected , or ; but got (local, "local")

      local procVolumeName = 'proc';
`

**Comment by brancz** [comment]
Oh. We didn't bump the dependency version, we should do that in the same PR (but separate commit).

**Pull request merged**
